name: Selenium BDD CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # Nightly regression at 2 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5-dind
        options: --privileged
        ports:
          - 4442:4442
          - 4443:4443
          - 4444:4444
          - 5900:5900
          - 5901:5900
          - 5902:5900
          - 7878:7878
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.6'

      - name: Start Selenium Grid and Healenium
        run: |
          docker-compose up -d

      - name: Wait for Selenium Grid and Healenium to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:4444/wd/hub/status | grep '"ready":true' && curl -s http://localhost:7878/healenium | grep 'UP'; then
              echo "Selenium Grid and Healenium are ready!"; break;
            fi
            echo "Waiting for Selenium Grid and Healenium..."; sleep 5;
          done

      - name: Run tests
        run: |
          mvn clean test -Dbrowser=chrome -Dheadless=true -Dselenium.grid.url=http://localhost:4444/wd/hub -Dhealenium.proxy.url=http://localhost:7878

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-results/

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: reports/

